### ISSUE TITLE
last tag version 가져올 때 버전이 1x로 올라가게 되면 생기는 이슈

### ISSUE THREAD

**Issue by light-src** [Sinhyeok/semver-ci#29]
## 이슈
gitlab project 내 v1.9.0, v1.10.0, v1.11.0 버전이 있을 때, last tag를 v1.9.0 으로 받아와 신규 버전을 v1.10.0-rc.COMMIT_SHA로 생성합니다

## 원인
https://github.com/Sinhyeok/semver-ci/blob/main/src/git_service.rs#L35
last version을 가져올 때, string 비교를 하기 때문에, 큰 값을 가져오는 것이 아닐까 싶습니다!

**Comment by Sinhyeok** [comment]
[v0.6.2](https://github.com/Sinhyeok/semver-ci/releases/tag/v0.6.2)에서 수정되었습니다. 제보 감사합니다 🚀
